#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# honestly might delete these precommits in favor of a github action instead
npm run dev:css
git add ./app/styles/**.css
npm run pretty-quick
npm run lint
npm run typecheck
